name: purplepig-gatsby
static_sites:
- build_command: pnpm build
  environment_slug: gatsby
  github:
    branch: main
    deploy_on_push: true
    repo: bodrick/purplepig-gatsby
  name: purplepig-gatsby
